In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [12]:
# preprocessing
df = pd.read_csv('./../0.data/heart_2020_cleaned.csv')

# replace 를 위한 함수 dataframe, column = 바꾸고자 하는 열 , text = 바꿀 문자열을 리스트로 넣어주면 list개수만큼 숫자로 변환해준다.
def exchange(DataFrame , column , *text):
    for i, t in enumerate(text[0]):
        DataFrame[column].replace(t,i,inplace = True)
# Yes or No 로 대답한 데이터들과 Female or Male 로 대답한 값에 대해 No = 0 Yes = 1로 replace 한 구분
# Diabetic은 예외적으로 4가지 경우에 대해서 올라와있었기에 0,1,2,3으로 카테고리화함   
exchange(df,'HeartDisease',['No','Yes'])
exchange(df,'Smoking',['No','Yes'])
exchange(df,'AlcoholDrinking',['No','Yes'])
exchange(df,'Stroke',['No','Yes'])
exchange(df,'DiffWalking',['No','Yes'])
exchange(df,'Sex',['Female','Male'])
exchange(df,'PhysicalActivity',['No','Yes'])
exchange(df,'Asthma',['No','Yes'])
exchange(df,'KidneyDisease',['No','Yes'])
exchange(df,'SkinCancer',['No','Yes'])
exchange(df,'Diabetic',['No','Yes','No, borderline diabetes','Yes (during pregnancy)'])

In [13]:
from sklearn.preprocessing import LabelEncoder
item = [ '18-24', '25-29', '30-34', '35-39','40-44','45-49', '50-54', '55-59', '60-64','65-69', '70-74','75-79','80 or older']
encoder = LabelEncoder()
encoder.fit(item)
labels = encoder.transform(df['AgeCategory'])
df['AgeCategory'] = pd.Series(labels)
df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,16.60,1,0,0,3.0,30.0,0,0,7,White,1,1,Very good,5.0,1,0,1
1,0,20.34,0,0,1,0.0,0.0,0,0,12,White,0,1,Very good,7.0,0,0,0
2,0,26.58,1,0,0,20.0,30.0,0,1,9,White,1,1,Fair,8.0,1,0,0
3,0,24.21,0,0,0,0.0,0.0,0,0,11,White,0,0,Good,6.0,0,0,1
4,0,23.71,0,0,0,28.0,0.0,1,0,4,White,0,1,Very good,8.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,7.0,0.0,1,1,8,Hispanic,1,0,Fair,6.0,1,0,0
319791,0,29.84,1,0,0,0.0,0.0,0,1,3,Hispanic,0,1,Very good,5.0,1,0,0
319792,0,24.24,0,0,0,0.0,0.0,0,0,5,Hispanic,0,1,Good,6.0,0,0,0
319793,0,32.81,0,0,0,0.0,0.0,0,0,1,Hispanic,0,0,Good,12.0,0,0,0
319794,0,46.56,0,0,0,0.0,0.0,0,0,12,Hispanic,0,1,Good,8.0,0,0,0

In [14]:
df['Race'].value_counts()

White                             245212
Hispanic                           27446
Black                              22939
Other                              10928
Asian                               8068
American Indian/Alaskan Native      5202
Name: Race, dtype: int64

In [15]:
item = ['White', 'Black', 'Asian', 'American Indian/Alaskan Native','Other', 'Hispanic']
encoder = LabelEncoder()
encoder.fit(item)
labels = encoder.transform(df['Race'])
df['Race'] = pd.Series(labels)
df['Race'].value_counts()

5    245212
3     27446
2     22939
4     10928
1      8068
0      5202
Name: Race, dtype: int64

In [16]:
df['GenHealth'].value_counts()

Very good    113858
Good          93129
Excellent     66842
Fair          34677
Poor          11289
Name: GenHealth, dtype: int64

In [17]:
from sklearn.preprocessing import LabelEncoder
item = df['GenHealth'].unique()
encoder = LabelEncoder()
encoder.fit(item)
labels = encoder.transform(df['GenHealth'])
df['GenHealth'] = pd.Series(labels)
df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,16.60,1,0,0,3.0,30.0,0,0,7,5,1,1,4,5.0,1,0,1
1,0,20.34,0,0,1,0.0,0.0,0,0,12,5,0,1,4,7.0,0,0,0
2,0,26.58,1,0,0,20.0,30.0,0,1,9,5,1,1,1,8.0,1,0,0
3,0,24.21,0,0,0,0.0,0.0,0,0,11,5,0,0,2,6.0,0,0,1
4,0,23.71,0,0,0,28.0,0.0,1,0,4,5,0,1,4,8.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,7.0,0.0,1,1,8,3,1,0,1,6.0,1,0,0
319791,0,29.84,1,0,0,0.0,0.0,0,1,3,3,0,1,4,5.0,1,0,0
319792,0,24.24,0,0,0,0.0,0.0,0,0,5,3,0,1,2,6.0,0,0,0
319793,0,32.81,0,0,0,0.0,0.0,0,0,1,3,0,0,2,12.0,0,0,0
319794,0,46.56,0,0,0,0.0,0.0,0,0,12,3,0,1,2,8.0,0,0,0

In [18]:
df.to_csv('heart_2020_cleaned_preprocessing.csv',index = False)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      319795 non-null  int64
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  int64
 3   AlcoholDrinking   319795 non-null  int64
 4   Stroke            319795 non-null  int64
 5   PhysicalHealth    319795 non-null  float64
 6   MentalHealth      319795 non-null  float64
 7   DiffWalking       319795 non-null  int64
 8   Sex               319795 non-null  int64
 9   AgeCategory       319795 non-null  int32
 10  Race              319795 non-null  int32
 11  Diabetic          319795 non-null  int64
 12  PhysicalActivity  319795 non-null  int64
 13  GenHealth         319795 non-null  int32
 14  SleepTime         319795 non-null  float64
 15  Asthma            319795 non-null  int64
 16  KidneyDisease     319795 non-null  int64
 17  SkinCancer        319795 non-null  int64
dtypes: float64(4), int32(3), int64(11)
memory usage: 40.3 MB

In [132]:
df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,16.60,1,0,0,3.0,30.0,0,0,7,5,1,1,4,5.0,1,0,1
1,0,20.34,0,0,1,0.0,0.0,0,0,12,5,0,1,4,7.0,0,0,0
2,0,26.58,1,0,0,20.0,30.0,0,1,9,5,1,1,1,8.0,1,0,0
3,0,24.21,0,0,0,0.0,0.0,0,0,11,5,0,0,2,6.0,0,0,1
4,0,23.71,0,0,0,28.0,0.0,1,0,4,5,0,1,4,8.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,7.0,0.0,1,1,8,3,1,0,1,6.0,1,0,0
319791,0,29.84,1,0,0,0.0,0.0,0,1,3,3,0,1,4,5.0,1,0,0
319792,0,24.24,0,0,0,0.0,0.0,0,0,5,3,0,1,2,6.0,0,0,0
319793,0,32.81,0,0,0,0.0,0.0,0,0,1,3,0,0,2,12.0,0,0,0
319794,0,46.56,0,0,0,0.0,0.0,0,0,12,3,0,1,2,8.0,0,0,0